---
- hosts: onprem
  tasks:
    - name: "Get number of processed records"
      ansible.builtin.shell: |
        podman exec db-container psql -U demo -d demo-db -c "select count(*) from work where nearprime is not null;"
      register: dbout
    - name: "Show number of processed records"
      debug:
        var: dbout
