---
- name: Deleting the nearestprime-db container
  containers.podman.podman_container:
    name: db-container
    image: quay.io/fgiorgetti/nearestprime-db
    state: absent
    network:
      - "{{ init.containerNetwork | default('skupper') }}"

- name: Deleting the nearestprime-load-gen container
  containers.podman.podman_container:
    name: load-gen-container
    image: quay.io/fgiorgetti/nearestprime-load-gen
    state: absent
    network:
      - "{{ init.containerNetwork | default('skupper') }}"

- name: Deleting the nearestprime podman network
  containers.podman.podman_network:
    name: "{{ init.containerNetwork | default('skupper') }}"
    state: absent
